[package]
name = "shader_builder"
version = "0.1.0"
authors = ["Inseok Lee <dlunch@gmail.com>"]
edition = "2018"

[lib]
doctest = false

[dependencies]
shaderc = { version = "^0.6", default-features = false }