[package]
name = "eng"
version = "0.1.0"
authors = ["Inseok Lee <dlunch@gmail.com>"]
edition = "2021"

[lib]
doctest = false

[dependencies]
futures = { version = "^0.3", features = ["async-await"], default-features = false }
log = { version = "^0.4", default-features = false }
wgpu = { version = "^0.12", features = ["webgl"], default-features = false }
zerocopy = { version = "^0.6", default-features = false }
nalgebra = { version = "^0.30", features = ["libm"], default-features = false }
squish = { version = "^1", default-features = false }
raw-window-handle = { version = "^0.4", default-features = false }
hashbrown = { version = "^0.12", features = ["ahash", "inline-more"], default-features = false }
spinning_top = { version = "^0.2", default-features = false }
naga = { version = "^0.8", features = ["wgsl-in" ] }
lazy_static = { version = "^1.4", default-features = false}

[dev-dependencies]
tokio = { version = "^1.12", features = ["full"] }
winit = { version = "^0.26", features = ["x11", "wayland"] }
pretty_env_logger = { version = "^0.4" }