[package]
name = "eng"
version = "0.1.0"
authors = ["Inseok Lee <dlunch@gmail.com>"]
edition = "2018"
resolver = "2"

[lib]
doctest = false

[dependencies]
futures = { version = "^0.3", features = ["async-await"], default-features = false }
log = { version = "^0.4", default-features = false }
wgpu = { version = "^0.11", features = ["webgl"], default-features = false }
zerocopy = { version = "^0.6", default-features = false }
nalgebra = { version = "^0.29", features = ["libm"], default-features = false }
squish = { version = "^1", default-features = false }
raw-window-handle = { version = "^0.3", default-features = false }
hashbrown = { version = "^0.11", features = ["ahash", "inline-more"], default-features = false }
spinning_top = { version = "^0.2", default-features = false }
naga = { version = "^0.8", features = ["wgsl-in" ]}

[dev-dependencies]
async-std = { version = "^1.6", features = ["attributes"] }
winit = { version = "^0.25", features = ["x11", "wayland"] }
pretty_env_logger = { version = "^0.4" }