[package]
name = "renderer"
version = "0.1.0"
authors = ["Inseok Lee <dlunch@gmail.com>"]
edition = "2018"

[lib]
doctest = false

[dependencies]
futures = { version = "^0.3", features = ["async-await"], default-features = false }
log = { version = "^0.4", default-features = false }
wgpu = { version = "^0.8", features = ["webgl"], default-features = false }
zerocopy = { version = "^0.5", default-features = false }
nalgebra = { version = "^0.26", features = ["libm"], default-features = false }
squish = { version = "^1", default-features = false }
raw-window-handle = { version = "^0.3", default-features = false }
hashbrown = { version = "^0.11", features = ["ahash", "inline-more"], default-features = false }
spinning_top = { version = "^0.2", default-features = false }

[dev-dependencies]
async-std = { version = "^1.6", features = ["default"], default-features = false }
winit = { version = "^0.24", features = ["x11", "wayland"], default-features = false }
pretty_env_logger = { version = "^0.4", default-features = false }

[build-dependencies]
shader_builder = { version = "^0.1", path = "./shader_builder" }

[workspace]
members = [
    "shader_builder",
]
